### PR TITLE
Parser interface

### PR DESCRIPTION
**Pull request by ladinesa**
Use parser class hierarchy with common parser method parse and abstract method write_to_archive.

### CODE REVIEW

**Review by JFRudzinski — APPROVED** [review]
Just a general question about parser maintenance: There are a number of these atomsitic parsers which only have a handful (or sometimes 0!) entries + I presume that the functionality of these parsers are not very good / up-to-date. We need to decide which parsers we continue to maintain and which we dump. I think the move to plugins is a reasonable time to make this decision.

Not sure what the best way to go about this other than recent usage. Anyway, not relevant for this MR, but we should discuss sometime.

**Comment by ladinesa** [comment]
> Just a general question about parser maintenance: There are a number of these atomsitic parsers which only have a handful (or sometimes 0!) entries + I presume that the functionality of these parsers are not very good / up-to-date. We need to decide which parsers we continue to maintain and which we dump. I think the move to plugins is a reasonable time to make this decision.
> 
> Not sure what the best way to go about this other than recent usage. Anyway, not relevant for this MR, but we should discuss sometime.

yes, we can certainly do this.

**Comment by ladinesa** [comment]
@JFRudzinski are we ok with this pr?

**Comment by JFRudzinski** [comment]
> @JFRudzinski are we ok with this pr?

Yes please go ahead

**Pull request merged**
