### PR TITLE
removed deprecated dependency on archive.m_context

### LINKED ISSUE #112: update gromacs parser

### PR DESCRIPTION
**Pull request by Bernadette-Mohr**

### CODE REVIEW

**Comment by JFRudzinski** [comment]
@ladinesa Can you take a look at this? The installation is suddenly failing in the pipeline. It was working fine when I made a PR last night. The changes in this PR have no connection with this, but just to be sure I made a simple copy of develop and just added a comment to the code, and get the same errors.

**Comment by ladinesa** [comment]
I think it is because mpcdf is down. maybe we can rerun later.

**Comment by JFRudzinski** [comment]
> I think it is because mpcdf is down. maybe we can rerun later.

oh ok, makes sense...I did not notice this, thanks

**Comment by JFRudzinski** [comment]
@Bernadette-Mohr It's fixed! You can go ahead and merge it now

**Pull request merged**
